name: Test definitions

on:
  push:
    branches:
      - "*"
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  Convert:
    name: Convert definitions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Set up Python ðŸ
      #   uses: actions/setup-python@v1
      #   with:
      #     python-version: 3.9

      # - name: Install python dependencies
      #   run: pip install data-product-definition-tooling

      # - name: Generate definitions
      #   run: converter src DataProducts

      - name: test
        run: date > data.txt

      - name: Check if requires a push
        run: [[-z $(git status -s)]]
        continue-on-error: true

      - name: Commit and push
        if: ${{ failure() }}
        run: |
          git config --local user.name "${BOT_NAME}"
          git config --local user.email "${BOT_EMAIL}"
          git add .
          git commit -m "Convert definitions" -a

          git push https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:${BRANCH}
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.ref }}
          BOT_NAME: github-actions[bot]
          BOT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
